# Site settings
title: Kyle Shiroma – Data Science Portfolio
description: Data Science and Machine Learning Portfolio
github: https://github.com/k-shiroma-code
linkedin: https://www.linkedin.com/in/k-shiroma
email: kyleshiroma77@gmail.com
show_downloads: true
url: "https://k-shiroma-code.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom CSS processing
sass:
  style: compressed
