# Site settings
title: Kyle Shiroma Portfolio
theme: jekyll-theme-minimal
github: https://github.com/k-shiroma-code
linkedin: https://www.linkedin.com/in/k-shiroma
email: kyleshiroma77@gmail.com
show_downloads: true
