# Site settings
title: Kyle Shiroma
description: I’m a data science enthusiast currently pursuing a B.S. in Data Science at UC San Diego. I have hands-on experience in machine learning, data analysis, and building production-ready pipelines.
#logo: /assets/img/headshot_circle.png
url: https://k-shiroma-code.github.io
baseurl: ""

# Theme
theme: jekyll-theme-minimal
show_downloads: true

# Personal info
email: kyleshiroma77@gmail.com
phone: 909-378-0684
github: https://github.com/k-shiroma-code
linkedin: https://www.linkedin.com/in/k-shiroma

# About Me (can be referenced in pages)
about_me: >
  I’m a data science enthusiast currently pursuing a B.S. in Data Science at UC San Diego.
  I have hands-on experience in machine learning, data analysis, and building production-ready pipelines.
  My passion lies in transforming raw data into actionable insights, optimizing predictive models, 
  and creating interactive visualizations. I’ve led teams in hackathons, completed data science 
  research internships, and enjoy tackling real-world problems with Python, SQL, and modern 
  data engineering tools.
